-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.BG_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("<time> during <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2076393647782445,
                               unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("<part-of-day> of <time>part of days", -2.4849066497880004),
                                    ("hourhour", -1.0185695809945732),
                                    ("minutehour", -2.890371757896165),
                                    ("at <time-of-day>part of days", -2.1972245773362196),
                                    ("intersectpart of days", -1.9740810260220096),
                                    ("<time-of-day> o'clockpart of days", -1.9740810260220096)],
                               n = 13},
                   koData =
                     ClassData{prior = -1.6739764335716716, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("yearhour", -2.0794415416798357),
                                    ("hourhour", -2.0794415416798357),
                                    ("hh:mmpart of days", -2.0794415416798357),
                                    ("minutehour", -2.0794415416798357),
                                    ("time-of-day (latent)part of days", -2.0794415416798357),
                                    ("year (latent)part of days", -2.0794415416798357)],
                               n = 3}}),
       ("Thursday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.6997917232786139, unseen = -4.343805421853684,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 75},
                   koData =
                     ClassData{prior = -0.6865464965285932, unseen = -4.356708826689592,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 76}}),
       ("<day-of-month> (ordinal or number) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.653960350157523,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal (digits)October", -3.951243718581427),
                                    ("ordinal (digit .)February", -3.951243718581427),
                                    ("ordinal (digit .)March", -3.0349529867072724),
                                    ("ordinal (digit .)October", -3.951243718581427),
                                    ("ordinals (first..19th)March", -3.545778610473263),
                                    ("ordinal (digits)February", -3.545778610473263),
                                    ("integer (numeric)April", -2.005333569526114),
                                    ("ordinal (digit .)April", -2.8526314299133175),
                                    ("integer (numeric)August", -3.951243718581427),
                                    ("integer (numeric)February", -3.0349529867072724),
                                    ("ordinal (digits)April", -3.951243718581427),
                                    ("month", -0.8377284093710529),
                                    ("ordinal (digits)March", -2.8526314299133175),
                                    ("integer (numeric)October", -3.951243718581427),
                                    ("integer (numeric)July", -3.545778610473263),
                                    ("integer (numeric)March", -3.951243718581427)],
                               n = 44},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2682639865946794,
                               unseen = -4.2626798770413155,
                               likelihoods =
                                 HashMap.fromList
                                   [("<part-of-day> of <time>part of days", -3.5553480614894135),
                                    ("hourhour", -1.157452788691043),
                                    ("hh:mmpart of days", -3.5553480614894135),
                                    ("<time-of-day> o'clockin|during the <part-of-day>",
                                     -2.639057329615259),
                                    ("minutehour", -2.456735772821304),
                                    ("at <time-of-day>part of days", -2.639057329615259),
                                    ("at <time-of-day>in|during the <part-of-day>",
                                     -2.8622008809294686),
                                    ("hhhpart of days", -3.5553480614894135),
                                    ("intersectpart of days", -3.5553480614894135),
                                    ("intersectin|during the <part-of-day>", -2.639057329615259),
                                    ("<part-of-day> of <time>in|during the <part-of-day>",
                                     -3.1498829533812494),
                                    ("time-of-day (latent)part of days", -2.8622008809294686),
                                    ("<hour-of-day> and <duration>part of days",
                                     -3.1498829533812494)],
                               n = 26},
                   koData =
                     ClassData{prior = -1.4469189829363254,
                               unseen = -3.5553480614894135,
                               likelihoods =
                                 HashMap.fromList
                                   [("yearhour", -2.4277482359480516),
                                    ("hourhour", -1.916922612182061),
                                    ("hh:mmpart of days", -2.833213344056216),
                                    ("minutehour", -2.4277482359480516),
                                    ("year (latent)in|during the <part-of-day>",
                                     -2.833213344056216),
                                    ("hh:mmin|during the <part-of-day>", -2.833213344056216),
                                    ("time-of-day (latent)in|during the <part-of-day>",
                                     -2.833213344056216),
                                    ("time-of-day (latent)part of days", -2.1400661634962708),
                                    ("year (latent)part of days", -2.833213344056216)],
                               n = 8}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.12136085700426748,
                               unseen = -4.248495242049359,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> o'clock", -2.624668592163159),
                                    ("<hour-of-day> and <integer>", -3.5409593240373143),
                                    ("time-of-day (latent)", -1.461517782357478),
                                    ("hh:mm", -2.624668592163159), ("hhh", -2.1546649629174235),
                                    ("hour", -0.9760099665757773), ("minute", -2.2881963555419462)],
                               n = 31},
                   koData =
                     ClassData{prior = -2.169053700369523, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0986122886681098),
                                    ("hour", -1.0986122886681098)],
                               n = 4}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -1.3862943611198906), ("Friday", -1.791759469228055),
                                    ("day", -0.8754687373538999), ("Sunday", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last|past|next <duration>",
        Classifier{okData =
                     ClassData{prior = -0.5753641449035618,
                               unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.4816045409242156), ("year", -2.3978952727983707),
                                    ("a <unit-of-duration>", -0.7884573603642702),
                                    ("month", -1.4816045409242156)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.8266785731844679,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.5040773967762742), ("year", -1.791759469228055),
                                    ("a <unit-of-duration>", -0.8109302162163288),
                                    ("month", -1.791759469228055)],
                               n = 7}}),
       ("in|during <named-month>|year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (latent)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = -8.701137698962981e-2,
                               unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.6863989535702288),
                                    ("time-of-day (latent)", -1.349926716949016),
                                    ("hh:mm", -2.6026896854443837), ("hour", -0.9932517730102834),
                                    ("minute", -2.1972245773362196)],
                               n = 11},
                   koData =
                     ClassData{prior = -2.4849066497880004,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.252762968495368),
                                    ("hour", -1.252762968495368)],
                               n = 1}}),
       ("nextyear2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("July",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17}}),
       ("composite <duration> (with ,/and)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourminute", -0.6931471805599453),
                                    ("integer (numeric)hour (grain)<integer> <unit-of-duration>",
                                     -0.6931471805599453)],
                               n = 3}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.29327180193056773,
                               unseen = -6.272877006546167,
                               likelihoods =
                                 HashMap.fromList
                                   [("Tuesdaylast|past|next <duration>", -5.577841251298354),
                                    ("this <day-of-week>this|last|next <cycle>",
                                     -5.577841251298354),
                                    ("last night<time-of-day> o'clock", -5.172376143190189),
                                    ("October<year>yr", -5.172376143190189),
                                    ("dayhour", -2.903692601871825),
                                    ("daymonth", -2.24563674112315),
                                    ("monthyear", -3.052112606990099),
                                    ("Mondaylast|past|next <duration>", -5.577841251298354),
                                    ("dd-mm-yyyyat <time-of-day>", -5.172376143190189),
                                    ("<day-of-month> (ordinal)October", -5.172376143190189),
                                    ("intersectat <time-of-day>", -4.325078282802986),
                                    ("Marchlast|past|next <duration>", -5.577841251298354),
                                    ("Octoberyear (latent)", -4.479228962630244),
                                    ("<day-of-month> (ordinal)last|past|next <duration>",
                                     -4.661550519424199),
                                    ("last night<time> during <part-of-day>", -4.661550519424199),
                                    ("<named-day> <ordinal>February", -5.577841251298354),
                                    ("Marchyear (latent)", -4.479228962630244),
                                    ("monthhour", -4.325078282802986),
                                    ("<day-of-month> (ordinal or number) <named-month><time> <part-of-day>",
                                     -4.661550519424199),
                                    ("Fridaythis|last|next <cycle>", -5.172376143190189),
                                    ("dayday", -4.325078282802986),
                                    ("<day-of-month> (ordinal or number) <named-month>at <time-of-day>",
                                     -3.5629382307560893),
                                    ("absorption of , after named day<day-of-month> (ordinal or number) <named-month>",
                                     -4.661550519424199),
                                    ("<day-of-month> (ordinal)intersect", -3.0929346015103536),
                                    ("hourhour", -2.660070519214075),
                                    ("Wednesdaythis|last|next <cycle>", -5.577841251298354),
                                    ("dayyear", -2.533318813574931),
                                    ("intersect<year>yr", -4.325078282802986),
                                    ("<time-of-day> o'clockin|during the <part-of-day>",
                                     -4.661550519424199),
                                    ("last nightintersect", -4.661550519424199),
                                    ("<day-of-month> (ordinal)mm.yyyy", -4.479228962630244),
                                    ("Aprilyear (latent)", -4.661550519424199),
                                    ("Fridaylast|past|next <duration>", -5.577841251298354),
                                    ("minutehour", -5.577841251298354),
                                    ("at <time-of-day>in|during the <part-of-day>",
                                     -4.8846940707384086),
                                    ("last night<time> <part-of-day>", -4.479228962630244),
                                    ("last nightat <time-of-day>", -3.968403338864254),
                                    ("<day-of-month> (ordinal)February", -4.8846940707384086),
                                    ("mm.yyyyat <time-of-day>", -5.172376143190189),
                                    ("<day-of-month> (ordinal or number) <named-month><year>yr",
                                     -4.07376385452208),
                                    ("Mondaythis|last|next <cycle>", -5.172376143190189),
                                    ("Marchthis|last|next <cycle>", -5.577841251298354),
                                    ("<day-of-month> (ordinal)this|last|next <cycle>",
                                     -4.325078282802986),
                                    ("intersectin|during the <part-of-day>", -4.661550519424199),
                                    ("<part-of-day> of <time>in|during the <part-of-day>",
                                     -5.172376143190189),
                                    ("<day-of-month> (ordinal or number) <named-month>year (latent)",
                                     -3.437775087802083),
                                    ("last|past|next <duration>on a <named-day>",
                                     -5.577841251298354),
                                    ("Tuesdaythis|last|next <cycle>", -5.577841251298354),
                                    ("dayminute", -4.07376385452208),
                                    ("<day-of-month> (ordinal or number) <named-month>intersect",
                                     -5.577841251298354),
                                    ("absorption of , after named dayintersect",
                                     -5.577841251298354),
                                    ("intersectyear (latent)", -3.786081782070299),
                                    ("<day-of-month> (ordinal or number) <named-month><time-of-day> o'clock",
                                     -5.172376143190189),
                                    ("April<year>yr", -4.661550519424199),
                                    ("<day-of-month> (ordinal)March", -3.786081782070299),
                                    ("this <time>this|last|next <cycle>", -5.577841251298354),
                                    ("weekday", -4.191546890178463),
                                    ("dayweek", -3.786081782070299),
                                    ("<day-of-month> (ordinal or number) <named-month><time> during <part-of-day>",
                                     -5.577841251298354),
                                    ("March<year>yr", -5.172376143190189),
                                    ("<day-of-month> (ordinal)April", -4.325078282802986),
                                    ("Sunday<day-of-month> (ordinal or number) <named-month>",
                                     -5.577841251298354),
                                    ("Aprilat <time-of-day>", -4.661550519424199),
                                    ("this|last|next <cycle>on a <named-day>", -4.325078282802986)],
                               n = 223},
                   koData =
                     ClassData{prior = -1.3697102331043554,
                               unseen = -5.4638318050256105,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -4.7664383335842135),
                                    ("dayhour", -3.0616902413457883),
                                    ("monthyear", -3.380143972464323),
                                    ("houryear", -3.5136753650888455),
                                    ("Octoberyear (latent)", -4.7664383335842135),
                                    ("time-of-day (latent)intersect", -3.5136753650888455),
                                    ("Marchyear (latent)", -4.7664383335842135),
                                    ("monthhour", -2.6263721700879428),
                                    ("hourmonth", -2.5692137562479944),
                                    ("dayday", -4.360973225476049),
                                    ("<day-of-month> (ordinal or number) <named-month>at <time-of-day>",
                                     -3.2623609368079394),
                                    ("<day-of-month> (ordinal)intersect", -4.360973225476049),
                                    ("hourhour", -4.7664383335842135),
                                    ("time-of-day (latent)February", -3.8501476017100584),
                                    ("dayyear", -4.073291153024268),
                                    ("intersect<year>yr", -4.360973225476049),
                                    ("Aprilyear (latent)", -4.073291153024268),
                                    ("monthminute", -3.0616902413457883),
                                    ("minutehour", -4.7664383335842135),
                                    ("April<time-of-day> o'clock", -4.360973225476049),
                                    ("April<time> during <part-of-day>", -4.7664383335842135),
                                    ("dayminute", -4.360973225476049),
                                    ("absorption of , after named dayintersect",
                                     -4.073291153024268),
                                    ("time-of-day (latent)March", -4.7664383335842135),
                                    ("intersectyear (latent)", -3.8501476017100584),
                                    ("time-of-day (latent)July", -4.360973225476049),
                                    ("April<year>yr", -4.360973225476049),
                                    ("<day-of-month> (ordinal)<year>yr", -4.073291153024268),
                                    ("hh:mmin|during the <part-of-day>", -4.7664383335842135),
                                    ("Aprilintersect", -4.7664383335842135),
                                    ("time-of-day (latent)in|during the <part-of-day>",
                                     -4.7664383335842135),
                                    ("time-of-day (latent)August", -4.7664383335842135),
                                    ("time-of-day (latent)intersect by \"\1085\1072\", \"\1087\1088\1077\1079\", \"\1079\1072\", \",\"",
                                     -4.7664383335842135),
                                    ("Aprilat <time-of-day>", -2.5151465349777182),
                                    ("Sundayintersect", -4.7664383335842135),
                                    ("time-of-day (latent)April", -4.073291153024268),
                                    ("April<time> <part-of-day>", -3.8501476017100584)],
                               n = 76}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -1.1451323043030026,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.38299225225610584,
                               unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15}}),
       ("Saturday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.3862943611198906),
                                    ("Monday", -1.791759469228055), ("day", -0.8754687373538999),
                                    ("Tuesday", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (latent)",
        Classifier{okData =
                     ClassData{prior = -9.53101798043249e-2,
                               unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 20},
                   koData =
                     ClassData{prior = -2.3978952727983707,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 2}}),
       ("suffixes (K,M,G))",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.2231435513142097),
                                    ("decimal number", -1.6094379124341003)],
                               n = 18}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("tomorrow+2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> and <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("hhh<integer> <unit-of-duration>", -1.0986122886681098),
                                    ("hourminute", -0.8109302162163288),
                                    ("<time-of-day> o'clock<integer> <unit-of-duration>",
                                     -1.5040773967762742)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd-mm-yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> and <integer>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.0149030205422647),
                                    ("hhhinteger (numeric)", -1.6094379124341003),
                                    ("hour", -0.916290731874155),
                                    ("at <time-of-day>integer (numeric)", -2.0149030205422647),
                                    ("<time-of-day> o'clockinteger (numeric)",
                                     -2.0149030205422647)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("April",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 19},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next2 <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("Friday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 19},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<part-of-day> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.6888794541139363,
                               likelihoods =
                                 HashMap.fromList
                                   [("last night<time-of-day> o'clock", -2.5649493574615367),
                                    ("last night<time> during <part-of-day>", -2.5649493574615367),
                                    ("hourhour", -0.8303483020734304),
                                    ("last nightintersect", -2.5649493574615367),
                                    ("last nighthhh", -2.5649493574615367),
                                    ("last night<time> <part-of-day>", -2.277267285009756),
                                    ("last nighttime-of-day (latent)", -1.8718021769015913)],
                               n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Friday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in|during the <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.6931471805599453),
                                    ("part of days", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -1.252762968495368), ("day", -0.8472978603872037),
                                    ("Sunday", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this|last|next <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.418840607796598,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.410986973710262),
                                    ("month (grain)", -2.0088239744658827),
                                    ("year (grain)", -2.327277705584417),
                                    ("week (grain)", -1.410986973710262),
                                    ("day", -3.713572066704308), ("year", -2.327277705584417),
                                    ("month", -2.0088239744658827),
                                    ("day (grain)", -3.713572066704308)],
                               n = 37},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = -0.1823215567939546, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.0149030205422647),
                                    ("Monday", -2.0149030205422647),
                                    ("Friday", -2.0149030205422647), ("day", -0.916290731874155),
                                    ("Tuesday", -1.6094379124341003)],
                               n = 5},
                   koData =
                     ClassData{prior = -1.791759469228055, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("Friday", -1.252762968495368), ("day", -1.252762968495368)],
                               n = 1}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("Sunday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("February",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.6190392084062235,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.13976194237515874),
                                    ("number (0..19)", -2.03688192726104)],
                               n = 21},
                   koData =
                     ClassData{prior = -0.7731898882334817, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -5.129329438755058e-2)],
                               n = 18}}),
       ("upcoming <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.4277482359480516, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)minute (grain)", -1.1786549963416462),
                                    ("minute", -1.1786549963416462)],
                               n = 3},
                   koData =
                     ClassData{prior = -9.237332013101517e-2,
                               unseen = -4.248495242049359,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)year (grain)", -1.461517782357478),
                                    ("year", -1.461517782357478),
                                    ("number (0..19)hour (grain)", -3.5409593240373143),
                                    ("hour", -1.4008931605410433),
                                    ("integer (numeric)hour (grain)", -1.461517782357478)],
                               n = 31}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("on <day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("<day-of-month> (ordinal)", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.093234863812172, unseen = -3.4339872044851463,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.791759469228055),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -2.70805020110221),
                                    ("week (grain)", -1.791759469228055),
                                    ("year", -2.70805020110221), ("month", -1.791759469228055)],
                               n = 9},
                   koData =
                     ClassData{prior = -0.13157635778871932,
                               unseen = -4.948759890378168,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.169053700369523),
                                    ("month (grain)", -2.995732273553991),
                                    ("hour (grain)", -2.05127066471314),
                                    ("year (grain)", -1.8505999692509885),
                                    ("week (grain)", -2.169053700369523),
                                    ("day", -3.8430301339411947),
                                    ("minute (grain)", -3.5553480614894135),
                                    ("year", -1.8505999692509885), ("hour", -2.05127066471314),
                                    ("month", -2.995732273553991), ("minute", -3.5553480614894135),
                                    ("day (grain)", -3.8430301339411947)],
                               n = 64}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -0.35667494393873245,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -1.2039728043259361,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("number (0..19)",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("yyyy-mm",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.8472978603872037), ("Sunday", -0.8472978603872037)],
                               n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.916290731874155), ("day", -0.916290731874155)],
                               n = 1}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.10265415406008334,
                               unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinals (first..19th)", -2.5902671654458267),
                                    ("ordinal (digit .)", -0.7444404749474959),
                                    ("ordinal (digits)", -0.7985076962177716)],
                               n = 37},
                   koData =
                     ClassData{prior = -2.327277705584417, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList [("ordinal (digit .)", -0.3364722366212129)],
                               n = 4}}),
       ("hhh",
        Classifier{okData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("on a <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.6739764335716716),
                                    ("Monday", -1.6739764335716716),
                                    ("Friday", -1.6739764335716716), ("day", -0.8266785731844679)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("nextyear",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16}}),
       ("<day-of-month>(ordinal or number).<named-month>.year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.060443010546419,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal (digits)October", -3.349904087274605),
                                    ("ordinal (digit .)March", -2.6567569067146595),
                                    ("ordinal (digit .)October", -3.349904087274605),
                                    ("integer (numeric)April", -1.9636097261547143),
                                    ("ordinal (digit .)April", -2.4336133554004498),
                                    ("month", -0.8241754429663495),
                                    ("ordinal (digits)March", -2.9444389791664407),
                                    ("integer (numeric)October", -2.9444389791664407),
                                    ("integer (numeric)March", -2.4336133554004498)],
                               n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -0.3184537311185346,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.4423470353692043),
                                    ("Friday", -2.03688192726104), ("day", -1.3437347467010947),
                                    ("March", -1.749199854809259), ("month", -1.749199854809259),
                                    ("Tuesday", -2.03688192726104)],
                               n = 8},
                   koData =
                     ClassData{prior = -1.2992829841302609, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -1.8718021769015913),
                                    ("Friday", -1.8718021769015913), ("day", -1.466337068793427),
                                    ("March", -1.8718021769015913), ("month", -1.8718021769015913)],
                               n = 3}}),
       ("negative numbers",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 6}}),
       ("Tuesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow+1",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("ordinal (digit .)",
        Classifier{okData =
                     ClassData{prior = -0.4769240720903093, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -0.9694005571881036,
                               unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11}}),
       ("mm.yyyy",
        Classifier{okData =
                     ClassData{prior = -0.13353139262452263,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -2.0794415416798357,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("last night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.995732273553991,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 18},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month> year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal (digits)October", -2.639057329615259),
                                    ("ordinal (digit .)March", -1.9459101490553135),
                                    ("ordinal (digit .)October", -2.639057329615259),
                                    ("ordinal (digit .)April", -1.7227665977411035),
                                    ("month", -0.8472978603872037),
                                    ("ordinal (digits)March", -2.2335922215070942)],
                               n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<year>yr",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 12},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 3}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("right now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-day> <ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("absorption of , after named dayordinal (digits)",
                                     -1.252762968495368),
                                    ("day", -0.8472978603872037),
                                    ("Tuesdayordinal (digits)", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("part of days",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect by \"\1085\1072\", \"\1087\1088\1077\1079\", \"\1079\1072\", \",\"",
        Classifier{okData =
                     ClassData{prior = -0.4418327522790392,
                               unseen = -3.5263605246161616,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday<day-of-month> (ordinal or number) <named-month>",
                                     -2.3978952727983707),
                                    ("Mondayintersect", -2.803360380906535),
                                    ("dayday", -1.1939224684724346),
                                    ("<day-of-month> (ordinal)Tuesday", -2.3978952727983707),
                                    ("Sunday<day-of-month> (ordinal or number) <named-month>",
                                     -2.803360380906535),
                                    ("Friday<day-of-month> (ordinal or number) <named-month>",
                                     -2.803360380906535),
                                    ("<day-of-month> (ordinal or number) <named-month>Friday",
                                     -2.803360380906535),
                                    ("<day-of-month> (ordinal)Thursday", -2.803360380906535)],
                               n = 9},
                   koData =
                     ClassData{prior = -1.0296194171811581, unseen = -3.258096538021482,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersectFriday", -2.5257286443082556),
                                    ("hourday", -2.5257286443082556),
                                    ("dayhour", -1.8325814637483102),
                                    ("monthday", -2.5257286443082556),
                                    ("Mondayintersect", -2.5257286443082556),
                                    ("JulyFriday", -2.5257286443082556),
                                    ("Fridayintersect", -2.5257286443082556),
                                    ("Sundayintersect", -2.5257286443082556)],
                               n = 5}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.2039728043259361), ("day", -0.916290731874155),
                                    ("Tuesday", -1.6094379124341003)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -1.0986122886681098), ("day", -1.0986122886681098)],
                               n = 1}}),
       ("<positive-numeral> <time-grain>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("year", -0.6931471805599453),
                                    ("decimal numberyear (grain)", -0.6931471805599453)],
                               n = 3}}),
       ("August",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}})]